server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

promo:
  offers:
    - offercode1:
        COMIC: 10
        FICTION: 5
    - offercode2:
        COMPUTER: 5
        SPIRITUAL: 10